// Code generated by nhatp.com/go/mock-gen/cmd/go-mock-gen - v0.1.0. DO NOT EDIT.

package example

import (
	"context"
	"fmt"
	"testing"
)

func Test_Repository_CreateUser(t *testing.T) {
	mock := testRepository()

	t.Run("expect called once", func(t *testing.T) {
		mock.EXPECT().CreateUser(t)

		var ctx context.Context
		var username string
		var age int
		mock.CreateUser(ctx, username, age)
	})

	t.Run("expect called twice", func(t *testing.T) {
		mock.EXPECT().CreateUser(t)
		mock.EXPECT().CreateUser(t)

		var ctx context.Context
		var username string
		var age int
		mock.CreateUser(ctx, username, age)
		mock.CreateUser(ctx, username, age)
	})

	t.Run("expect called - stub return", func(t *testing.T) {
		var first User
		var second error

		mock.EXPECT().CreateUser(t).Return(first, second)

		var ctx context.Context
		var username string
		var age int
		ret0, ret1 := mock.CreateUser(ctx, username, age)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("expect called - match all arguments by values", func(t *testing.T) {
		var ctx context.Context
		var username string
		var age int

		mock.EXPECT().CreateUser(t).With(ctx, username, age)

		mock.CreateUser(ctx, username, age)
	})

	t.Run("expect called - match all arguments by values - stub return", func(t *testing.T) {
		var ctx context.Context
		var username string
		var age int
		var first User
		var second error

		mock.EXPECT().CreateUser(t).With(ctx, username, age).Return(first, second)

		ret0, ret1 := mock.CreateUser(ctx, username, age)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("expect called - match partial argument by value", func(t *testing.T) {
		var ctx context.Context

		mock.EXPECT().CreateUser(t).WithCtx(ctx)

		var username string
		var age int
		mock.CreateUser(ctx, username, age)
	})

	t.Run("expect called - match partial by value - stub return", func(t *testing.T) {
		var ctx context.Context
		var first User
		var second error

		mock.EXPECT().CreateUser(t).WithCtx(ctx).Return(first, second)

		var username string
		var age int
		ret0, ret1 := mock.CreateUser(ctx, username, age)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("expect called - match all arguments by callback", func(t *testing.T) {
		mock.EXPECT().CreateUser(t).Match(func(ctx context.Context, username string, age int) bool {
			return true
		})

		var ctx context.Context
		var username string
		var age int
		mock.CreateUser(ctx, username, age)
	})

	t.Run("expect called - match all arguments by callback - stub return", func(t *testing.T) {
		var first User
		var second error

		mock.EXPECT().CreateUser(t).Match(func(ctx context.Context, username string, age int) bool {
			return true
		}).Return(first, second)

		var ctx context.Context
		var username string
		var age int
		ret0, ret1 := mock.CreateUser(ctx, username, age)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("expect called - match partial argument by callback", func(t *testing.T) {
		mock.EXPECT().CreateUser(t).MatchCtx(func(ctx context.Context) bool {
			return true
		})

		var ctx context.Context
		var username string
		var age int
		mock.CreateUser(ctx, username, age)
	})

	t.Run("expect called - match partial by callback - stub return", func(t *testing.T) {
		var first User
		var second error

		mock.EXPECT().CreateUser(t).MatchCtx(func(ctx context.Context) bool {
			return true
		}).Return(first, second)

		var ctx context.Context
		var username string
		var age int
		ret0, ret1 := mock.CreateUser(ctx, username, age)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("fine-grained control with stub signature", func(t *testing.T) {
		mock = testRepository()
		spy := mock.STUB().CreateUser(func(ctx context.Context, username string, age int) (User, error) {
			return User{}, nil
		})

		var ctx context.Context
		var username string
		var age int
		mock.CreateUser(ctx, username, age)

		fmt.Println(spy)
	})
}

func Test_Repository_GetUsers(t *testing.T) {
	mock := testRepository()

	t.Run("expect called once", func(t *testing.T) {
		mock.EXPECT().GetUsers(t)

		var ctx context.Context
		mock.GetUsers(ctx)
	})

	t.Run("expect called twice", func(t *testing.T) {
		mock.EXPECT().GetUsers(t)
		mock.EXPECT().GetUsers(t)

		var ctx context.Context
		mock.GetUsers(ctx)
		mock.GetUsers(ctx)
	})

	t.Run("expect called - stub return", func(t *testing.T) {
		var first []User
		var second error

		mock.EXPECT().GetUsers(t).Return(first, second)

		var ctx context.Context
		ret0, ret1 := mock.GetUsers(ctx)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("expect called - match all arguments by values", func(t *testing.T) {
		var ctx context.Context

		mock.EXPECT().GetUsers(t).With(ctx)

		mock.GetUsers(ctx)
	})

	t.Run("expect called - match all arguments by values - stub return", func(t *testing.T) {
		var ctx context.Context
		var first []User
		var second error

		mock.EXPECT().GetUsers(t).With(ctx).Return(first, second)

		ret0, ret1 := mock.GetUsers(ctx)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("expect called - match partial argument by value", func(t *testing.T) {
		var ctx context.Context

		mock.EXPECT().GetUsers(t).WithCtx(ctx)

		mock.GetUsers(ctx)
	})

	t.Run("expect called - match partial by value - stub return", func(t *testing.T) {
		var ctx context.Context
		var first []User
		var second error

		mock.EXPECT().GetUsers(t).WithCtx(ctx).Return(first, second)

		ret0, ret1 := mock.GetUsers(ctx)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("expect called - match all arguments by callback", func(t *testing.T) {
		mock.EXPECT().GetUsers(t).Match(func(ctx context.Context) bool {
			return true
		})

		var ctx context.Context
		mock.GetUsers(ctx)
	})

	t.Run("expect called - match all arguments by callback - stub return", func(t *testing.T) {
		var first []User
		var second error

		mock.EXPECT().GetUsers(t).Match(func(ctx context.Context) bool {
			return true
		}).Return(first, second)

		var ctx context.Context
		ret0, ret1 := mock.GetUsers(ctx)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("expect called - match partial argument by callback", func(t *testing.T) {
		mock.EXPECT().GetUsers(t).MatchCtx(func(ctx context.Context) bool {
			return true
		})

		var ctx context.Context
		mock.GetUsers(ctx)
	})

	t.Run("expect called - match partial by callback - stub return", func(t *testing.T) {
		var first []User
		var second error

		mock.EXPECT().GetUsers(t).MatchCtx(func(ctx context.Context) bool {
			return true
		}).Return(first, second)

		var ctx context.Context
		ret0, ret1 := mock.GetUsers(ctx)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("fine-grained control with stub signature", func(t *testing.T) {
		mock = testRepository()
		spy := mock.STUB().GetUsers(func(ctx context.Context) ([]User, error) {
			return nil, nil
		})

		var ctx context.Context
		mock.GetUsers(ctx)

		fmt.Println(spy)
	})
}
