// Code generated by nhatp.com/go/mock-gen/cmd/go-mock-gen - v0.1.0. DO NOT EDIT.

package mock

import (
	"context"
	"fmt"
	example "nhatp.com/go/mock-gen/example"
	"path/filepath"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func mockgenCallerLocation(skip int) string {
	_, file, line, _ := runtime.Caller(skip)
	return fmt.Sprintf("%s:%d", filepath.Base(file), line)
}

type mockgenMockMethod interface {
	methodName() string
	interfaceName() string
	buildCallHistory(sb *strings.Builder, header string)
	fatal(index int, msg string)
	panic(msg string)
}

func mockgenMessageWriteArguments(sb *strings.Builder, template string, args []any) {
	maxLen := 0
	for i := 0; i < len(args); i += 2 {
		str, ok := args[i].(string)
		if !ok {
			str = fmt.Sprintf("%v", args[i])
		}
		maxLen = max(maxLen, len(str))
	}

	format := strings.ReplaceAll(template, "[MAX-KEY-LEN]", strconv.Itoa(maxLen))
	for i := 0; i < len(args); i += 2 {
		key, ok := args[i].(string)
		if !ok {
			key = fmt.Sprintf("%v", args[i])
		}

		var val any
		if i+1 < len(args) {
			val = args[i+1]
		}
		sb.WriteString(fmt.Sprintf(format, key, val))
	}
}

func mockgenMessageMatchFail(m mockgenMockMethod, matchedAt string, index int, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s call #%d did not match\n", m.interfaceName(), m.methodName(), index+1))
	sb.WriteString(fmt.Sprintf("arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	m.buildCallHistory(sb, "call history")
	sb.WriteString(fmt.Sprintf("hint: check the callback passed to Match at %s", matchedAt))
	return sb.String()
}

func mockgenMessageNotImplemented(interfaceName string, methodName string, signature string, createdLocation string, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("unexpected call to %s.%s\n", interfaceName, methodName))
	sb.WriteString(fmt.Sprintf("signature: %s.%s%s\n", interfaceName, methodName, signature))
	sb.WriteString(fmt.Sprintf("called at: %s\n", mockgenCallerLocation(3)))
	sb.WriteString("arguments:\n")
	mockgenMessageWriteArguments(sb, "\t%[MAX-KEY-LEN]s = %#v\n", args)

	location := ""
	if createdLocation != "" {
		location = " after " + createdLocation
	}
	sb.WriteString(fmt.Sprintf("\nhint:%s use one of:\n\t[var].EXPECT().%s(t)\n\t[var].STUB().%s(func(...) ...)\n\n", location, methodName, methodName))
	return sb.String()
}

func mockgenMessageCallHistory(sb *strings.Builder, index int, expectedAt string, calledAt string, args []any) string {
	sb.WriteString(fmt.Sprintf("\t#%d expect at: %s\n", index+1, expectedAt))
	sb.WriteString(fmt.Sprintf("\t   called at: %s\n", calledAt))
	sb.WriteString(fmt.Sprintf("\t   arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	return sb.String()
}

func mockgenMessageTooManyCalls(m mockgenMockMethod, want int, got int, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("too many calls to %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\twant: %d, got: %d\n\n", want, got))
	m.buildCallHistory(sb, "")
	sb.WriteString(fmt.Sprintf("\t#%d expect at: %s\n", got, "missing"))
	sb.WriteString(fmt.Sprintf("\t   called at: %s\n", mockgenCallerLocation(4)))
	sb.WriteString(fmt.Sprintf("\t   arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("\thint: remove unexpected call or add 1 more EXPECT:\n\t\t[var].EXPECT().%s(t)\n", m.methodName()))
	return sb.String()
}

func mockgenMessageMatchByNil(m mockgenMockMethod) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s Match received a nil function\n", m.interfaceName(), m.methodName()))
	sb.WriteString("\thint: provide a valid function")
	return sb.String()
}

func mockgenMessageExpectByNil(m mockgenMockMethod) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("unexpected nil testing.TB in %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\tcalled at: %s\n\n", mockgenCallerLocation(3)))
	sb.WriteString("\thint: EXPECT requires a valid testing.TB, use STUB instead:\n")
	sb.WriteString(fmt.Sprintf("\t\tspy := [var].STUB().%s(func(...) ...)\n", m.methodName()))
	return sb.String()
}

func mockgenMessageExpectAfterStub(m mockgenMockMethod, stubAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("conflicting usage for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "STUB used at", stubAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "EXPECT used at", mockgenCallerLocation(3)))
	sb.WriteString("\thint: use either EXPECT or STUB for the same method, not both\n\n")
	return sb.String()
}

func mockgenMessageStubByNil(m mockgenMockMethod, calledAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s STUB received a nil function\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("called at: %s\n\n", calledAt))
	sb.WriteString("hint: provide a valid function\n")
	return sb.String()
}

func mockgenMessageStubAfterExpect(m mockgenMockMethod, expectAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("conflicting usage for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "EXPECT used at", expectAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "STUB used at", mockgenCallerLocation(3)))
	sb.WriteString("\thint: use either EXPECT or STUB for the same method, not both\n\n")
	return sb.String()
}

func mockgenMessageDuplicateStub(m mockgenMockMethod, firstUsedAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("duplicate STUB for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "first used at", firstUsedAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "second used at", mockgenCallerLocation(3)))
	sb.WriteString(fmt.Sprintf("\thint: %s.%s is already stubbed, remove one of the above\n\n", m.interfaceName(), m.methodName()))
	return sb.String()
}

func mockgenMessageExpectButNotCalled(m mockgenMockMethod, want int, got int, index int) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s was not called as expected\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\twant: %d, got: %d\n\n", want, got))
	m.buildCallHistory(sb, "")
	sb.WriteString(fmt.Sprintf("\t#%d never called\n\n", index+1))
	sb.WriteString("\thint: add the missing call or remove the EXPECT above")
	return sb.String()
}

func mockgenMessageMatchArgByNil(m mockgenMockMethod, method string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s %s received a nil function\n", m.interfaceName(), m.methodName(), method))
	sb.WriteString("\thint: provide a valid function")
	return sb.String()
}

func mockgenMessageDuplicateMatchArg(m mockgenMockMethod, method string, firstUsedAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("duplicate %s for %s.%s\n", method, m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "first used at", firstUsedAt))
	sb.WriteString("\thint: each argument can only be matched once, remove one of the above")
	return sb.String()
}

func mockgenMessageMatchArgHint() string {
	return fmt.Sprintf("\thint: check argument matching at %s\n\t\tor use STUB for fine-grained control", mockgenCallerLocation(3))
}

func mockgenMatchArgument[T any](m mockgenMockMethod, index int, name string, got T, match func(T) bool, wants map[string]any, methods map[string]string, hints map[string]string, tb testing.TB, expectAt string) {
	if match == nil || match(got) {
		return
	}
	tb.Helper()

	method := "func(got) bool"
	if v, ok := methods[name]; ok {
		method = v
	}

	hint := fmt.Sprintf("hint: for custom matching use .Match[arg](func(...) bool) at %s\n\tor use STUB for fine-grained control", expectAt)
	if v, ok := hints[name]; ok {
		hint = v
	}

	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s call #%d argument \"%s\" did not match\n", m.interfaceName(), m.methodName(), index+1, name))
	if want, ok := wants[name]; ok {
		sb.WriteString(fmt.Sprintf("  want: %#v\n", want))
	}
	sb.WriteString(fmt.Sprintf("   got: %#v\n", got))
	sb.WriteString(fmt.Sprintf("method: %s\n", method))
	sb.WriteString("\n")
	m.buildCallHistory(sb, "call history")
	sb.WriteString(hint)

	tb.Helper()
	m.fatal(index, sb.String())
}

func mockgenReflectEqualMatcher[T any](want T) func(T) bool {
	return func(got T) bool {
		return reflect.DeepEqual(want, got)
	}
}

func mockgenBasicComparisonMatcher[T comparable](want T) func(T) bool {
	return func(got T) bool {
		return want == got
	}
}

func NewRepository() *Repository {
	return &Repository{td: &RepositoryTestDouble{location: mockgenCallerLocation(2)}}
}

type RepositoryTestDouble struct {
	location   string
	CreateUser *RepositoryCreateUser
	GetUsers   *RepositoryGetUsers
}

type Repository struct {
	td *RepositoryTestDouble
}

func (m *Repository) STUB() *RepositoryStubber {
	return &RepositoryStubber{target: m}
}

func (m *Repository) EXPECT() *RepositoryExpecter {
	return &RepositoryExpecter{target: m}
}

func (m *Repository) CreateUser(ctx context.Context, username string, age int) (example.User, error) {
	v0, v1, v2 := "Repository", "CreateUser", "(ctx Context, username string, age int) (User, error)"
	v3 := []any{"ctx", ctx, "username", username, "age", age}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.CreateUser; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(ctx, username, age)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(ctx, username, age)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *Repository) GetUsers(ctx context.Context) ([]example.User, error) {
	v0, v1, v2 := "Repository", "GetUsers", "(ctx Context) ([]User, error)"
	v3 := []any{"ctx", ctx}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.GetUsers; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(ctx)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(ctx)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

type RepositoryStubber struct {
	target *Repository
}

func (s *RepositoryStubber) CreateUser(stub func(ctx context.Context, username string, age int) (example.User, error)) *RepositoryCreateUser {
	if s.target.td == nil {
		s.target.td = &RepositoryTestDouble{}
	}

	m := s.target.td.CreateUser
	if m == nil {
		m = &RepositoryCreateUser{stubLocation: mockgenCallerLocation(2)}
		s.target.td.CreateUser = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *RepositoryStubber) GetUsers(stub func(ctx context.Context) ([]example.User, error)) *RepositoryGetUsers {
	if s.target.td == nil {
		s.target.td = &RepositoryTestDouble{}
	}

	m := s.target.td.GetUsers
	if m == nil {
		m = &RepositoryGetUsers{stubLocation: mockgenCallerLocation(2)}
		s.target.td.GetUsers = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

type RepositoryExpecter struct {
	target *Repository
}

func (e *RepositoryExpecter) CreateUser(tb testing.TB) *RepositoryCreateUserExpecter {
	if e.target.td == nil {
		e.target.td = &RepositoryTestDouble{}
	}

	var m = e.target.td.CreateUser
	if m == nil {
		m = &RepositoryCreateUser{}
		e.target.td.CreateUser = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &RepositoryCreateUserExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &RepositoryCreateUserArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &RepositoryCreateUserExpecter{target: m, expect: m.expects[idx]}
}

func (e *RepositoryExpecter) GetUsers(tb testing.TB) *RepositoryGetUsersExpecter {
	if e.target.td == nil {
		e.target.td = &RepositoryTestDouble{}
	}

	var m = e.target.td.GetUsers
	if m == nil {
		m = &RepositoryGetUsers{}
		e.target.td.GetUsers = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &RepositoryGetUsersExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &RepositoryGetUsersArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &RepositoryGetUsersExpecter{target: m, expect: m.expects[idx]}
}

type RepositoryCreateUser struct {
	Calls        []RepositoryCreateUserCall
	stub         func(ctx context.Context, username string, age int) (example.User, error)
	stubLocation string
	expects      []*RepositoryCreateUserExpect
	verified     bool
}

func (m *RepositoryCreateUser) methodName() string {
	return "CreateUser"
}

func (m *RepositoryCreateUser) interfaceName() string {
	return "Repository"
}

func (m *RepositoryCreateUser) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *RepositoryCreateUser) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *RepositoryCreateUser) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"ctx", v.Argument.Ctx, "username", v.Argument.Username, "age", v.Argument.Age}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *RepositoryCreateUser) invokeStub(ctx context.Context, username string, age int) (example.User, error) {
	v0, v1 := m.stub(ctx, username, age)
	return m.capture(RepositoryCreateUserArgument{Ctx: ctx, Username: username, Age: age}, RepositoryCreateUserReturn{First: v0, Second: v1})
}

func (m *RepositoryCreateUser) invokeExpect(ctx context.Context, username string, age int) (example.User, error) {
	v0 := []any{"ctx", ctx, "username", username, "age", age}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(ctx, username, age) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "ctx", ctx, v2.matcher.ctx, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["ctx"])
	mockgenMatchArgument(m, v1, "username", username, v2.matcher.username, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["username"])
	mockgenMatchArgument(m, v1, "age", age, v2.matcher.age, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["age"])

	return m.capture(RepositoryCreateUserArgument{Ctx: ctx, Username: username, Age: age}, v2.returns)
}

func (m *RepositoryCreateUser) capture(args RepositoryCreateUserArgument, returns RepositoryCreateUserReturn) (example.User, error) {
	m.Calls = append(m.Calls, RepositoryCreateUserCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.First, returns.Second
}

func (m *RepositoryCreateUser) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type RepositoryCreateUserCall struct {
	Location string
	Argument RepositoryCreateUserArgument
	Return   RepositoryCreateUserReturn
}

type RepositoryCreateUserArgument struct {
	Ctx      context.Context
	Username string
	Age      int
}

type RepositoryCreateUserArgumentMatcher struct {
	ctx      func(ctx context.Context) bool
	username func(username string) bool
	age      func(age int) bool
}

type RepositoryCreateUserReturn struct {
	First  example.User
	Second error
}

type RepositoryCreateUserExpect struct {
	match            func(ctx context.Context, username string, age int) bool
	matchLocation    string
	matcher          *RepositoryCreateUserArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          RepositoryCreateUserReturn
	location         string
	index            int
	tb               testing.TB
}

type RepositoryCreateUserExpecter struct {
	expect *RepositoryCreateUserExpect
	target *RepositoryCreateUser
}

func (e *RepositoryCreateUserExpecter) Return(first example.User, second error) {
	e.expect.returns = RepositoryCreateUserReturn{First: first, Second: second}
}

func (e *RepositoryCreateUserExpecter) Match(matcher func(ctx context.Context, username string, age int) bool) *RepositoryCreateUserExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &RepositoryCreateUserExpecterWithMatch{expect: e.expect}
}

func (e *RepositoryCreateUserExpecter) MatchCtx(matcher func(ctx context.Context) bool) *RepositoryCreateUserExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCtx"))
	}

	e.expect.matcher.ctx = matcher
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)
	e.expect.matcherHints["ctx"] = mockgenMessageMatchArgHint()
	return &RepositoryCreateUserExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *RepositoryCreateUserExpecter) MatchUsername(matcher func(username string) bool) *RepositoryCreateUserExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchUsername"))
	}

	e.expect.matcher.username = matcher
	e.expect.matcherLocations["username"] = mockgenCallerLocation(2)
	e.expect.matcherHints["username"] = mockgenMessageMatchArgHint()
	return &RepositoryCreateUserExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *RepositoryCreateUserExpecter) MatchAge(matcher func(age int) bool) *RepositoryCreateUserExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchAge"))
	}

	e.expect.matcher.age = matcher
	e.expect.matcherLocations["age"] = mockgenCallerLocation(2)
	e.expect.matcherHints["age"] = mockgenMessageMatchArgHint()
	return &RepositoryCreateUserExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *RepositoryCreateUserExpecter) With(ctx context.Context, username string, age int) *RepositoryCreateUserExpecterWithValue {
	e.WithCtx(ctx)
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)

	e.WithUsername(username)
	e.expect.matcherLocations["username"] = mockgenCallerLocation(2)

	e.WithAge(age)
	e.expect.matcherLocations["age"] = mockgenCallerLocation(2)

	return &RepositoryCreateUserExpecterWithValue{expect: e.expect}
}

func (e *RepositoryCreateUserExpecter) WithCtx(ctx context.Context) *RepositoryCreateUserExpecterWithValueArg {
	e.expect.matcher.ctx = mockgenBasicComparisonMatcher(ctx)
	e.expect.matcherWants["ctx"] = ctx
	e.expect.matcherMethods["ctx"] = "=="
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)

	return &RepositoryCreateUserExpecterWithValueArg{expect: e.expect, target: e.target}
}

func (e *RepositoryCreateUserExpecter) WithUsername(username string) *RepositoryCreateUserExpecterWithValueArg {
	e.expect.matcher.username = mockgenBasicComparisonMatcher(username)
	e.expect.matcherWants["username"] = username
	e.expect.matcherMethods["username"] = "=="
	e.expect.matcherLocations["username"] = mockgenCallerLocation(2)

	return &RepositoryCreateUserExpecterWithValueArg{expect: e.expect, target: e.target}
}

func (e *RepositoryCreateUserExpecter) WithAge(age int) *RepositoryCreateUserExpecterWithValueArg {
	e.expect.matcher.age = mockgenBasicComparisonMatcher(age)
	e.expect.matcherWants["age"] = age
	e.expect.matcherMethods["age"] = "=="
	e.expect.matcherLocations["age"] = mockgenCallerLocation(2)

	return &RepositoryCreateUserExpecterWithValueArg{expect: e.expect, target: e.target}
}

type RepositoryCreateUserExpecterWithMatch struct {
	expect *RepositoryCreateUserExpect
}

func (e *RepositoryCreateUserExpecterWithMatch) Return(first example.User, second error) {
	e.expect.returns = RepositoryCreateUserReturn{First: first, Second: second}
}

type RepositoryCreateUserExpecterWithMatchArg struct {
	expect *RepositoryCreateUserExpect
	target *RepositoryCreateUser
}

func (e *RepositoryCreateUserExpecterWithMatchArg) Return(first example.User, second error) {
	e.expect.returns = RepositoryCreateUserReturn{First: first, Second: second}
}

func (e *RepositoryCreateUserExpecterWithMatchArg) MatchCtx(matcher func(ctx context.Context) bool) *RepositoryCreateUserExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCtx"))
	}

	if e.expect.matcher.ctx != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCtx", e.expect.matcherLocations["ctx"]))
	}

	e.expect.matcher.ctx = matcher
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)
	e.expect.matcherHints["ctx"] = mockgenMessageMatchArgHint()
	return e
}

func (e *RepositoryCreateUserExpecterWithMatchArg) MatchUsername(matcher func(username string) bool) *RepositoryCreateUserExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchUsername"))
	}

	if e.expect.matcher.username != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchUsername", e.expect.matcherLocations["username"]))
	}

	e.expect.matcher.username = matcher
	e.expect.matcherLocations["username"] = mockgenCallerLocation(2)
	e.expect.matcherHints["username"] = mockgenMessageMatchArgHint()
	return e
}

func (e *RepositoryCreateUserExpecterWithMatchArg) MatchAge(matcher func(age int) bool) *RepositoryCreateUserExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchAge"))
	}

	if e.expect.matcher.age != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchAge", e.expect.matcherLocations["age"]))
	}

	e.expect.matcher.age = matcher
	e.expect.matcherLocations["age"] = mockgenCallerLocation(2)
	e.expect.matcherHints["age"] = mockgenMessageMatchArgHint()
	return e
}

type RepositoryCreateUserExpecterWithValue struct {
	expect *RepositoryCreateUserExpect
}

func (e *RepositoryCreateUserExpecterWithValue) Return(first example.User, second error) {
	e.expect.returns = RepositoryCreateUserReturn{First: first, Second: second}
}

type RepositoryCreateUserExpecterWithValueArg struct {
	expect *RepositoryCreateUserExpect
	target *RepositoryCreateUser
}

func (e *RepositoryCreateUserExpecterWithValueArg) Return(first example.User, second error) {
	e.expect.returns = RepositoryCreateUserReturn{First: first, Second: second}
}

func (e *RepositoryCreateUserExpecterWithValueArg) WithCtx(ctx context.Context) *RepositoryCreateUserExpecterWithValueArg {
	if e.expect.matcher.ctx != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCtx", e.expect.matcherLocations["ctx"]))
	}

	e.expect.matcher.ctx = mockgenBasicComparisonMatcher(ctx)
	e.expect.matcherWants["ctx"] = ctx
	e.expect.matcherMethods["ctx"] = "=="
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)

	return e
}

func (e *RepositoryCreateUserExpecterWithValueArg) WithUsername(username string) *RepositoryCreateUserExpecterWithValueArg {
	if e.expect.matcher.username != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithUsername", e.expect.matcherLocations["username"]))
	}

	e.expect.matcher.username = mockgenBasicComparisonMatcher(username)
	e.expect.matcherWants["username"] = username
	e.expect.matcherMethods["username"] = "=="
	e.expect.matcherLocations["username"] = mockgenCallerLocation(2)

	return e
}

func (e *RepositoryCreateUserExpecterWithValueArg) WithAge(age int) *RepositoryCreateUserExpecterWithValueArg {
	if e.expect.matcher.age != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithAge", e.expect.matcherLocations["age"]))
	}

	e.expect.matcher.age = mockgenBasicComparisonMatcher(age)
	e.expect.matcherWants["age"] = age
	e.expect.matcherMethods["age"] = "=="
	e.expect.matcherLocations["age"] = mockgenCallerLocation(2)

	return e
}

type RepositoryGetUsers struct {
	Calls        []RepositoryGetUsersCall
	stub         func(ctx context.Context) ([]example.User, error)
	stubLocation string
	expects      []*RepositoryGetUsersExpect
	verified     bool
}

func (m *RepositoryGetUsers) methodName() string {
	return "GetUsers"
}

func (m *RepositoryGetUsers) interfaceName() string {
	return "Repository"
}

func (m *RepositoryGetUsers) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *RepositoryGetUsers) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *RepositoryGetUsers) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"ctx", v.Argument.Ctx}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *RepositoryGetUsers) invokeStub(ctx context.Context) ([]example.User, error) {
	v0, v1 := m.stub(ctx)
	return m.capture(RepositoryGetUsersArgument{Ctx: ctx}, RepositoryGetUsersReturn{First: v0, Second: v1})
}

func (m *RepositoryGetUsers) invokeExpect(ctx context.Context) ([]example.User, error) {
	v0 := []any{"ctx", ctx}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(ctx) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "ctx", ctx, v2.matcher.ctx, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["ctx"])

	return m.capture(RepositoryGetUsersArgument{Ctx: ctx}, v2.returns)
}

func (m *RepositoryGetUsers) capture(args RepositoryGetUsersArgument, returns RepositoryGetUsersReturn) ([]example.User, error) {
	m.Calls = append(m.Calls, RepositoryGetUsersCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.First, returns.Second
}

func (m *RepositoryGetUsers) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type RepositoryGetUsersCall struct {
	Location string
	Argument RepositoryGetUsersArgument
	Return   RepositoryGetUsersReturn
}

type RepositoryGetUsersArgument struct {
	Ctx context.Context
}

type RepositoryGetUsersArgumentMatcher struct {
	ctx func(ctx context.Context) bool
}

type RepositoryGetUsersReturn struct {
	First  []example.User
	Second error
}

type RepositoryGetUsersExpect struct {
	match            func(ctx context.Context) bool
	matchLocation    string
	matcher          *RepositoryGetUsersArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          RepositoryGetUsersReturn
	location         string
	index            int
	tb               testing.TB
}

type RepositoryGetUsersExpecter struct {
	expect *RepositoryGetUsersExpect
	target *RepositoryGetUsers
}

func (e *RepositoryGetUsersExpecter) Return(first []example.User, second error) {
	e.expect.returns = RepositoryGetUsersReturn{First: first, Second: second}
}

func (e *RepositoryGetUsersExpecter) Match(matcher func(ctx context.Context) bool) *RepositoryGetUsersExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &RepositoryGetUsersExpecterWithMatch{expect: e.expect}
}

func (e *RepositoryGetUsersExpecter) MatchCtx(matcher func(ctx context.Context) bool) *RepositoryGetUsersExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCtx"))
	}

	e.expect.matcher.ctx = matcher
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)
	e.expect.matcherHints["ctx"] = mockgenMessageMatchArgHint()
	return &RepositoryGetUsersExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *RepositoryGetUsersExpecter) With(ctx context.Context) *RepositoryGetUsersExpecterWithValue {
	e.WithCtx(ctx)
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)

	return &RepositoryGetUsersExpecterWithValue{expect: e.expect}
}

func (e *RepositoryGetUsersExpecter) WithCtx(ctx context.Context) *RepositoryGetUsersExpecterWithValueArg {
	e.expect.matcher.ctx = mockgenBasicComparisonMatcher(ctx)
	e.expect.matcherWants["ctx"] = ctx
	e.expect.matcherMethods["ctx"] = "=="
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)

	return &RepositoryGetUsersExpecterWithValueArg{expect: e.expect, target: e.target}
}

type RepositoryGetUsersExpecterWithMatch struct {
	expect *RepositoryGetUsersExpect
}

func (e *RepositoryGetUsersExpecterWithMatch) Return(first []example.User, second error) {
	e.expect.returns = RepositoryGetUsersReturn{First: first, Second: second}
}

type RepositoryGetUsersExpecterWithMatchArg struct {
	expect *RepositoryGetUsersExpect
	target *RepositoryGetUsers
}

func (e *RepositoryGetUsersExpecterWithMatchArg) Return(first []example.User, second error) {
	e.expect.returns = RepositoryGetUsersReturn{First: first, Second: second}
}

func (e *RepositoryGetUsersExpecterWithMatchArg) MatchCtx(matcher func(ctx context.Context) bool) *RepositoryGetUsersExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCtx"))
	}

	if e.expect.matcher.ctx != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCtx", e.expect.matcherLocations["ctx"]))
	}

	e.expect.matcher.ctx = matcher
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)
	e.expect.matcherHints["ctx"] = mockgenMessageMatchArgHint()
	return e
}

type RepositoryGetUsersExpecterWithValue struct {
	expect *RepositoryGetUsersExpect
}

func (e *RepositoryGetUsersExpecterWithValue) Return(first []example.User, second error) {
	e.expect.returns = RepositoryGetUsersReturn{First: first, Second: second}
}

type RepositoryGetUsersExpecterWithValueArg struct {
	expect *RepositoryGetUsersExpect
	target *RepositoryGetUsers
}

func (e *RepositoryGetUsersExpecterWithValueArg) Return(first []example.User, second error) {
	e.expect.returns = RepositoryGetUsersReturn{First: first, Second: second}
}

func (e *RepositoryGetUsersExpecterWithValueArg) WithCtx(ctx context.Context) *RepositoryGetUsersExpecterWithValueArg {
	if e.expect.matcher.ctx != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCtx", e.expect.matcherLocations["ctx"]))
	}

	e.expect.matcher.ctx = mockgenBasicComparisonMatcher(ctx)
	e.expect.matcherWants["ctx"] = ctx
	e.expect.matcherMethods["ctx"] = "=="
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)

	return e
}
