// Code generated by nhatp.com/go/mock-gen/cmd/go-mock-gen - v0.1.0. DO NOT EDIT.

package integration

import (
	"context"
	"fmt"
	"testing"
)

func Test_Repository_Begin(t *testing.T) {
	mock := testRepository()

	t.Run("expect called once", func(t *testing.T) {
		mock.EXPECT().Begin(t)

		mock.Begin()
	})

	t.Run("expect called twice", func(t *testing.T) {
		mock.EXPECT().Begin(t)
		mock.EXPECT().Begin(t)

		mock.Begin()
		mock.Begin()
	})

	t.Run("fine-grained control with stub signature", func(t *testing.T) {
		mock = testRepository()
		spy := mock.STUB().Begin(func() {

		})

		mock.Begin()

		fmt.Println(spy)
	})
}
func Test_Repository_Count(t *testing.T) {
	mock := testRepository()

	t.Run("expect called once", func(t *testing.T) {
		mock.EXPECT().Count(t)

		mock.Count()
	})

	t.Run("expect called twice", func(t *testing.T) {
		mock.EXPECT().Count(t)
		mock.EXPECT().Count(t)

		mock.Count()
		mock.Count()
	})

	t.Run("expect called - stub return", func(t *testing.T) {
		var first int

		mock.EXPECT().Count(t).Return(first)

		ret0 := mock.Count()
		fmt.Println(ret0, first)
	})

	t.Run("fine-grained control with stub signature", func(t *testing.T) {
		mock = testRepository()
		spy := mock.STUB().Count(func() int {
			return 0
		})

		mock.Count()

		fmt.Println(spy)
	})
}
func Test_Repository_CreateUser(t *testing.T) {
	mock := testRepository()

	t.Run("expect called once", func(t *testing.T) {
		mock.EXPECT().CreateUser(t)

		var ctx context.Context
		var user User
		mock.CreateUser(ctx, user)
	})

	t.Run("expect called twice", func(t *testing.T) {
		mock.EXPECT().CreateUser(t)
		mock.EXPECT().CreateUser(t)

		var ctx context.Context
		var user User
		mock.CreateUser(ctx, user)
		mock.CreateUser(ctx, user)
	})

	t.Run("expect called - stub return", func(t *testing.T) {
		var first error

		mock.EXPECT().CreateUser(t).Return(first)

		var ctx context.Context
		var user User
		ret0 := mock.CreateUser(ctx, user)
		fmt.Println(ret0, first)
	})

	t.Run("expect called - match all arguments by values", func(t *testing.T) {
		var ctx context.Context
		var user User

		mock.EXPECT().CreateUser(t).With(ctx, user)

		mock.CreateUser(ctx, user)
	})

	t.Run("expect called - match all arguments by values - stub return", func(t *testing.T) {
		var ctx context.Context
		var user User
		var first error

		mock.EXPECT().CreateUser(t).With(ctx, user).Return(first)

		ret0 := mock.CreateUser(ctx, user)
		fmt.Println(ret0, first)
	})

	t.Run("expect called - match partial argument by value", func(t *testing.T) {
		var ctx context.Context

		mock.EXPECT().CreateUser(t).WithCtx(ctx)

		var user User
		mock.CreateUser(ctx, user)
	})

	t.Run("expect called - match partial by value - stub return", func(t *testing.T) {
		var ctx context.Context
		var first error

		mock.EXPECT().CreateUser(t).WithCtx(ctx).Return(first)

		var user User
		ret0 := mock.CreateUser(ctx, user)
		fmt.Println(ret0, first)
	})

	t.Run("expect called - match all arguments by callback", func(t *testing.T) {
		mock.EXPECT().CreateUser(t).Match(func(ctx context.Context, user User) bool {
			return true
		})

		var ctx context.Context
		var user User
		mock.CreateUser(ctx, user)
	})

	t.Run("expect called - match all arguments by callback - stub return", func(t *testing.T) {
		var first error

		mock.EXPECT().CreateUser(t).Match(func(ctx context.Context, user User) bool {
			return true
		}).Return(first)

		var ctx context.Context
		var user User
		ret0 := mock.CreateUser(ctx, user)
		fmt.Println(ret0, first)
	})

	t.Run("expect called - match partial argument by callback", func(t *testing.T) {
		mock.EXPECT().CreateUser(t).MatchCtx(func(ctx context.Context) bool {
			return true
		})

		var ctx context.Context
		var user User
		mock.CreateUser(ctx, user)
	})

	t.Run("expect called - match partial by callback - stub return", func(t *testing.T) {
		var first error

		mock.EXPECT().CreateUser(t).MatchCtx(func(ctx context.Context) bool {
			return true
		}).Return(first)

		var ctx context.Context
		var user User
		ret0 := mock.CreateUser(ctx, user)
		fmt.Println(ret0, first)
	})

	t.Run("fine-grained control with stub signature", func(t *testing.T) {
		mock = testRepository()
		spy := mock.STUB().CreateUser(func(ctx context.Context, user User) error {
			return nil
		})

		var ctx context.Context
		var user User
		mock.CreateUser(ctx, user)

		fmt.Println(spy)
	})
}
func Test_Repository_GetUsers(t *testing.T) {
	mock := testRepository()

	t.Run("expect called once", func(t *testing.T) {
		mock.EXPECT().GetUsers(t)

		var ctx context.Context
		var tenantID string
		mock.GetUsers(ctx, tenantID)
	})

	t.Run("expect called twice", func(t *testing.T) {
		mock.EXPECT().GetUsers(t)
		mock.EXPECT().GetUsers(t)

		var ctx context.Context
		var tenantID string
		mock.GetUsers(ctx, tenantID)
		mock.GetUsers(ctx, tenantID)
	})

	t.Run("expect called - stub return", func(t *testing.T) {
		var first []User
		var second error

		mock.EXPECT().GetUsers(t).Return(first, second)

		var ctx context.Context
		var tenantID string
		ret0, ret1 := mock.GetUsers(ctx, tenantID)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("expect called - match all arguments by values", func(t *testing.T) {
		var ctx context.Context
		var tenantID string

		mock.EXPECT().GetUsers(t).With(ctx, tenantID)

		mock.GetUsers(ctx, tenantID)
	})

	t.Run("expect called - match all arguments by values - stub return", func(t *testing.T) {
		var ctx context.Context
		var tenantID string
		var first []User
		var second error

		mock.EXPECT().GetUsers(t).With(ctx, tenantID).Return(first, second)

		ret0, ret1 := mock.GetUsers(ctx, tenantID)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("expect called - match partial argument by value", func(t *testing.T) {
		var ctx context.Context

		mock.EXPECT().GetUsers(t).WithCtx(ctx)

		var tenantID string
		mock.GetUsers(ctx, tenantID)
	})

	t.Run("expect called - match partial by value - stub return", func(t *testing.T) {
		var ctx context.Context
		var first []User
		var second error

		mock.EXPECT().GetUsers(t).WithCtx(ctx).Return(first, second)

		var tenantID string
		ret0, ret1 := mock.GetUsers(ctx, tenantID)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("expect called - match all arguments by callback", func(t *testing.T) {
		mock.EXPECT().GetUsers(t).Match(func(ctx context.Context, tenantID string) bool {
			return true
		})

		var ctx context.Context
		var tenantID string
		mock.GetUsers(ctx, tenantID)
	})

	t.Run("expect called - match all arguments by callback - stub return", func(t *testing.T) {
		var first []User
		var second error

		mock.EXPECT().GetUsers(t).Match(func(ctx context.Context, tenantID string) bool {
			return true
		}).Return(first, second)

		var ctx context.Context
		var tenantID string
		ret0, ret1 := mock.GetUsers(ctx, tenantID)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("expect called - match partial argument by callback", func(t *testing.T) {
		mock.EXPECT().GetUsers(t).MatchCtx(func(ctx context.Context) bool {
			return true
		})

		var ctx context.Context
		var tenantID string
		mock.GetUsers(ctx, tenantID)
	})

	t.Run("expect called - match partial by callback - stub return", func(t *testing.T) {
		var first []User
		var second error

		mock.EXPECT().GetUsers(t).MatchCtx(func(ctx context.Context) bool {
			return true
		}).Return(first, second)

		var ctx context.Context
		var tenantID string
		ret0, ret1 := mock.GetUsers(ctx, tenantID)
		fmt.Println(ret0, first)
		fmt.Println(ret1, second)
	})

	t.Run("fine-grained control with stub signature", func(t *testing.T) {
		mock = testRepository()
		spy := mock.STUB().GetUsers(func(ctx context.Context, tenantID string) ([]User, error) {
			return nil, nil
		})

		var ctx context.Context
		var tenantID string
		mock.GetUsers(ctx, tenantID)

		fmt.Println(spy)
	})
}
func Test_Service_VeryComplicated(t *testing.T) {
	mock := testService()

	t.Run("fine-grained control with stub signature", func(t *testing.T) {
		mock = testService()
		spy := mock.STUB().VeryComplicated(func(id int) error {
			return nil
		})

		var id int
		mock.VeryComplicated(id)

		fmt.Println(spy)
	})
}
