// Code generated by nhatp.com/go/mock-gen/cmd/go-mock-gen - v0.1.1. DO NOT EDIT.

package integration

import (
	"context"
	"fmt"
	"path/filepath"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func mockgenCallerLocation(skip int) string {
	_, file, line, _ := runtime.Caller(skip)
	return fmt.Sprintf("%s:%d", filepath.Base(file), line)
}

type mockgenMockMethod interface {
	methodName() string
	interfaceName() string
	buildCallHistory(sb *strings.Builder, header string)
	fatal(index int, msg string)
	panic(msg string)
}

func mockgenMessageWriteArguments(sb *strings.Builder, template string, args []any) {
	maxLen := 0
	for i := 0; i < len(args); i += 2 {
		str, ok := args[i].(string)
		if !ok {
			str = fmt.Sprintf("%v", args[i])
		}
		maxLen = max(maxLen, len(str))
	}

	format := strings.ReplaceAll(template, "[MAX-KEY-LEN]", strconv.Itoa(maxLen))
	for i := 0; i < len(args); i += 2 {
		key, ok := args[i].(string)
		if !ok {
			key = fmt.Sprintf("%v", args[i])
		}

		var val any
		if i+1 < len(args) {
			val = args[i+1]
		}
		sb.WriteString(fmt.Sprintf(format, key, val))
	}
}

func mockgenMessageMatchFail(m mockgenMockMethod, matchedAt string, index int, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s call #%d did not match\n", m.interfaceName(), m.methodName(), index+1))
	sb.WriteString(fmt.Sprintf("arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	m.buildCallHistory(sb, "call history")
	sb.WriteString(fmt.Sprintf("hint: check the callback passed to Match at %s", matchedAt))
	return sb.String()
}

func mockgenMessageNotImplemented(interfaceName string, methodName string, signature string, createdLocation string, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("unexpected call to %s.%s\n", interfaceName, methodName))
	sb.WriteString(fmt.Sprintf("signature: %s.%s%s\n", interfaceName, methodName, signature))
	sb.WriteString(fmt.Sprintf("called at: %s\n", mockgenCallerLocation(3)))
	sb.WriteString("arguments:\n")
	mockgenMessageWriteArguments(sb, "\t%[MAX-KEY-LEN]s = %#v\n", args)

	location := ""
	if createdLocation != "" {
		location = " after " + createdLocation
	}
	sb.WriteString(fmt.Sprintf("\nhint:%s use one of:\n\t[var].EXPECT().%s(t)\n\t[var].STUB().%s(func(...) ...)\n\n", location, methodName, methodName))
	return sb.String()
}

func mockgenMessageCallHistory(sb *strings.Builder, index int, expectedAt string, calledAt string, args []any) string {
	sb.WriteString(fmt.Sprintf("\t#%d expect at: %s\n", index+1, expectedAt))
	sb.WriteString(fmt.Sprintf("\t   called at: %s\n", calledAt))
	sb.WriteString(fmt.Sprintf("\t   arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	return sb.String()
}

func mockgenMessageTooManyCalls(m mockgenMockMethod, want int, got int, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("too many calls to %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\twant: %d, got: %d\n\n", want, got))
	m.buildCallHistory(sb, "")
	sb.WriteString(fmt.Sprintf("\t#%d expect at: %s\n", got, "missing"))
	sb.WriteString(fmt.Sprintf("\t   called at: %s\n", mockgenCallerLocation(4)))
	sb.WriteString(fmt.Sprintf("\t   arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("\thint: remove unexpected call or add 1 more EXPECT:\n\t\t[var].EXPECT().%s(t)\n", m.methodName()))
	return sb.String()
}

func mockgenMessageMatchByNil(m mockgenMockMethod) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s Match received a nil function\n", m.interfaceName(), m.methodName()))
	sb.WriteString("\thint: provide a valid function")
	return sb.String()
}

func mockgenMessageExpectByNil(m mockgenMockMethod) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("unexpected nil testing.TB in %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\tcalled at: %s\n\n", mockgenCallerLocation(3)))
	sb.WriteString("\thint: EXPECT requires a valid testing.TB, use STUB instead:\n")
	sb.WriteString(fmt.Sprintf("\t\tspy := [var].STUB().%s(func(...) ...)\n", m.methodName()))
	return sb.String()
}

func mockgenMessageExpectAfterStub(m mockgenMockMethod, stubAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("conflicting usage for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "STUB used at", stubAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "EXPECT used at", mockgenCallerLocation(3)))
	sb.WriteString("\thint: use either EXPECT or STUB for the same method, not both\n\n")
	return sb.String()
}

func mockgenMessageStubByNil(m mockgenMockMethod, calledAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s STUB received a nil function\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("called at: %s\n\n", calledAt))
	sb.WriteString("hint: provide a valid function\n")
	return sb.String()
}

func mockgenMessageStubAfterExpect(m mockgenMockMethod, expectAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("conflicting usage for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "EXPECT used at", expectAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "STUB used at", mockgenCallerLocation(3)))
	sb.WriteString("\thint: use either EXPECT or STUB for the same method, not both\n\n")
	return sb.String()
}

func mockgenMessageDuplicateStub(m mockgenMockMethod, firstUsedAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("duplicate STUB for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "first used at", firstUsedAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "second used at", mockgenCallerLocation(3)))
	sb.WriteString(fmt.Sprintf("\thint: %s.%s is already stubbed, remove one of the above\n\n", m.interfaceName(), m.methodName()))
	return sb.String()
}

func mockgenMessageExpectButNotCalled(m mockgenMockMethod, want int, got int, index int) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s was not called as expected\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\twant: %d, got: %d\n\n", want, got))
	m.buildCallHistory(sb, "")
	sb.WriteString(fmt.Sprintf("\t#%d never called\n\n", index+1))
	sb.WriteString("\thint: add the missing call or remove the EXPECT above")
	return sb.String()
}

func mockgenMessageMatchArgByNil(m mockgenMockMethod, method string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s %s received a nil function\n", m.interfaceName(), m.methodName(), method))
	sb.WriteString("\thint: provide a valid function")
	return sb.String()
}

func mockgenMessageDuplicateMatchArg(m mockgenMockMethod, method string, firstUsedAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("duplicate %s for %s.%s\n", method, m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "first used at", firstUsedAt))
	sb.WriteString("\thint: each argument can only be matched once, remove one of the above")
	return sb.String()
}

func mockgenMessageMatchArgHint() string {
	return fmt.Sprintf("\thint: check argument matching at %s\n\t\tor use STUB for fine-grained control", mockgenCallerLocation(3))
}

func mockgenMatchArgument[T any](m mockgenMockMethod, index int, name string, got T, match func(T) bool, wants map[string]any, methods map[string]string, hints map[string]string, tb testing.TB, expectAt string) {
	if match == nil || match(got) {
		return
	}
	tb.Helper()

	method := "func(got) bool"
	if v, ok := methods[name]; ok {
		method = v
	}

	hint := fmt.Sprintf("hint: for custom matching use .Match[arg](func(...) bool) at %s\n\tor use STUB for fine-grained control", expectAt)
	if v, ok := hints[name]; ok {
		hint = v
	}

	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s call #%d argument \"%s\" did not match\n", m.interfaceName(), m.methodName(), index+1, name))
	if want, ok := wants[name]; ok {
		sb.WriteString(fmt.Sprintf("  want: %#v\n", want))
	}
	sb.WriteString(fmt.Sprintf("   got: %#v\n", got))
	sb.WriteString(fmt.Sprintf("method: %s\n", method))
	sb.WriteString("\n")
	m.buildCallHistory(sb, "call history")
	sb.WriteString(hint)

	tb.Helper()
	m.fatal(index, sb.String())
}

func mockgenReflectEqualMatcher[T any](want T) func(T) bool {
	return func(got T) bool {
		return reflect.DeepEqual(want, got)
	}
}

func mockgenBasicComparisonMatcher[T comparable](want T) func(T) bool {
	return func(got T) bool {
		return want == got
	}
}

func testRepository() *repository {
	return &repository{td: &repositoryTestDouble{location: mockgenCallerLocation(2)}}
}

type repositoryTestDouble struct {
	location   string
	Begin      *repositoryBegin
	Count      *repositoryCount
	CreateUser *repositoryCreateUser
	GetUsers   *repositoryGetUsers
}

type repository struct {
	td *repositoryTestDouble
}

func (m *repository) STUB() *repositoryStubber {
	return &repositoryStubber{target: m}
}

func (m *repository) EXPECT() *repositoryExpecter {
	return &repositoryExpecter{target: m}
}

func (m *repository) Begin() {
	v0, v1, v2 := "Repository", "Begin", "()"
	v3 := []any{}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.Begin; v4 != nil {
		switch {
		case v4.stub != nil:
			v4.invokeStub()
			return
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			v4.invokeExpect()
			return
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *repository) Count() int {
	v0, v1, v2 := "Repository", "Count", "() int"
	v3 := []any{}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.Count; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub()
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect()
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *repository) CreateUser(ctx context.Context, user User) error {
	v0, v1, v2 := "Repository", "CreateUser", "(ctx Context, user User) error"
	v3 := []any{"ctx", ctx, "user", user}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.CreateUser; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(ctx, user)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(ctx, user)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *repository) GetUsers(ctx context.Context, tenantID string) ([]User, error) {
	v0, v1, v2 := "Repository", "GetUsers", "(ctx Context, tenantID string) ([]User, error)"
	v3 := []any{"ctx", ctx, "tenantID", tenantID}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.GetUsers; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(ctx, tenantID)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(ctx, tenantID)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

type repositoryStubber struct {
	target *repository
}

func (s *repositoryStubber) Begin(stub func()) *repositoryBegin {
	if s.target.td == nil {
		s.target.td = &repositoryTestDouble{}
	}

	m := s.target.td.Begin
	if m == nil {
		m = &repositoryBegin{stubLocation: mockgenCallerLocation(2)}
		s.target.td.Begin = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *repositoryStubber) Count(stub func() int) *repositoryCount {
	if s.target.td == nil {
		s.target.td = &repositoryTestDouble{}
	}

	m := s.target.td.Count
	if m == nil {
		m = &repositoryCount{stubLocation: mockgenCallerLocation(2)}
		s.target.td.Count = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *repositoryStubber) CreateUser(stub func(ctx context.Context, user User) error) *repositoryCreateUser {
	if s.target.td == nil {
		s.target.td = &repositoryTestDouble{}
	}

	m := s.target.td.CreateUser
	if m == nil {
		m = &repositoryCreateUser{stubLocation: mockgenCallerLocation(2)}
		s.target.td.CreateUser = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *repositoryStubber) GetUsers(stub func(ctx context.Context, tenantID string) ([]User, error)) *repositoryGetUsers {
	if s.target.td == nil {
		s.target.td = &repositoryTestDouble{}
	}

	m := s.target.td.GetUsers
	if m == nil {
		m = &repositoryGetUsers{stubLocation: mockgenCallerLocation(2)}
		s.target.td.GetUsers = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

type repositoryExpecter struct {
	target *repository
}

func (e *repositoryExpecter) Begin(tb testing.TB) {
	if e.target.td == nil {
		e.target.td = &repositoryTestDouble{}
	}

	var m = e.target.td.Begin
	if m == nil {
		m = &repositoryBegin{}
		e.target.td.Begin = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &repositoryBeginExpect{
		location: mockgenCallerLocation(2),
		index:    idx,
		tb:       tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})
}

func (e *repositoryExpecter) Count(tb testing.TB) *repositoryCountExpecter {
	if e.target.td == nil {
		e.target.td = &repositoryTestDouble{}
	}

	var m = e.target.td.Count
	if m == nil {
		m = &repositoryCount{}
		e.target.td.Count = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &repositoryCountExpect{
		location: mockgenCallerLocation(2),
		index:    idx,
		tb:       tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &repositoryCountExpecter{expect: m.expects[idx]}
}

func (e *repositoryExpecter) CreateUser(tb testing.TB) *repositoryCreateUserExpecter {
	if e.target.td == nil {
		e.target.td = &repositoryTestDouble{}
	}

	var m = e.target.td.CreateUser
	if m == nil {
		m = &repositoryCreateUser{}
		e.target.td.CreateUser = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &repositoryCreateUserExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &repositoryCreateUserArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &repositoryCreateUserExpecter{target: m, expect: m.expects[idx]}
}

func (e *repositoryExpecter) GetUsers(tb testing.TB) *repositoryGetUsersExpecter {
	if e.target.td == nil {
		e.target.td = &repositoryTestDouble{}
	}

	var m = e.target.td.GetUsers
	if m == nil {
		m = &repositoryGetUsers{}
		e.target.td.GetUsers = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &repositoryGetUsersExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &repositoryGetUsersArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &repositoryGetUsersExpecter{target: m, expect: m.expects[idx]}
}

type repositoryBegin struct {
	Calls        []repositoryBeginCall
	stub         func()
	stubLocation string
	expects      []*repositoryBeginExpect
	verified     bool
}

func (m *repositoryBegin) methodName() string {
	return "Begin"
}

func (m *repositoryBegin) interfaceName() string {
	return "Repository"
}

func (m *repositoryBegin) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *repositoryBegin) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *repositoryBegin) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *repositoryBegin) invokeStub() {
	m.stub()
	m.capture()
}

func (m *repositoryBegin) invokeExpect() {
	v0 := []any{}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	m.capture()
}

func (m *repositoryBegin) capture() {
	m.Calls = append(m.Calls, repositoryBeginCall{Location: mockgenCallerLocation(4)})
}

func (m *repositoryBegin) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type repositoryBeginCall struct {
	Location string
}

type repositoryBeginExpect struct {
	location string
	index    int
	tb       testing.TB
}

type repositoryCount struct {
	Calls        []repositoryCountCall
	stub         func() int
	stubLocation string
	expects      []*repositoryCountExpect
	verified     bool
}

func (m *repositoryCount) methodName() string {
	return "Count"
}

func (m *repositoryCount) interfaceName() string {
	return "Repository"
}

func (m *repositoryCount) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *repositoryCount) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *repositoryCount) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *repositoryCount) invokeStub() int {
	v0 := m.stub()
	return m.capture(repositoryCountReturn{first: v0})
}

func (m *repositoryCount) invokeExpect() int {
	v0 := []any{}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	return m.capture(v2.returns)
}

func (m *repositoryCount) capture(returns repositoryCountReturn) int {
	m.Calls = append(m.Calls, repositoryCountCall{Location: mockgenCallerLocation(4), Return: returns})
	return returns.first
}

func (m *repositoryCount) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type repositoryCountCall struct {
	Location string
	Return   repositoryCountReturn
}

type repositoryCountReturn struct {
	first int
}

type repositoryCountExpect struct {
	returns  repositoryCountReturn
	location string
	index    int
	tb       testing.TB
}

type repositoryCountExpecter struct {
	expect *repositoryCountExpect
}

func (e *repositoryCountExpecter) Return(first int) {
	e.expect.returns = repositoryCountReturn{first: first}
}

type repositoryCreateUser struct {
	Calls        []repositoryCreateUserCall
	stub         func(ctx context.Context, user User) error
	stubLocation string
	expects      []*repositoryCreateUserExpect
	verified     bool
}

func (m *repositoryCreateUser) methodName() string {
	return "CreateUser"
}

func (m *repositoryCreateUser) interfaceName() string {
	return "Repository"
}

func (m *repositoryCreateUser) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *repositoryCreateUser) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *repositoryCreateUser) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"ctx", v.Argument.ctx, "user", v.Argument.user}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *repositoryCreateUser) invokeStub(ctx context.Context, user User) error {
	v0 := m.stub(ctx, user)
	return m.capture(repositoryCreateUserArgument{ctx: ctx, user: user}, repositoryCreateUserReturn{first: v0})
}

func (m *repositoryCreateUser) invokeExpect(ctx context.Context, user User) error {
	v0 := []any{"ctx", ctx, "user", user}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(ctx, user) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "ctx", ctx, v2.matcher.ctx, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["ctx"])
	mockgenMatchArgument(m, v1, "user", user, v2.matcher.user, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["user"])

	return m.capture(repositoryCreateUserArgument{ctx: ctx, user: user}, v2.returns)
}

func (m *repositoryCreateUser) capture(args repositoryCreateUserArgument, returns repositoryCreateUserReturn) error {
	m.Calls = append(m.Calls, repositoryCreateUserCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first
}

func (m *repositoryCreateUser) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type repositoryCreateUserCall struct {
	Location string
	Argument repositoryCreateUserArgument
	Return   repositoryCreateUserReturn
}

type repositoryCreateUserArgument struct {
	ctx  context.Context
	user User
}

type repositoryCreateUserArgumentMatcher struct {
	ctx  func(ctx context.Context) bool
	user func(user User) bool
}

type repositoryCreateUserReturn struct {
	first error
}

type repositoryCreateUserExpect struct {
	match            func(ctx context.Context, user User) bool
	matchLocation    string
	matcher          *repositoryCreateUserArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          repositoryCreateUserReturn
	location         string
	index            int
	tb               testing.TB
}

type repositoryCreateUserExpecter struct {
	expect *repositoryCreateUserExpect
	target *repositoryCreateUser
}

func (e *repositoryCreateUserExpecter) Return(first error) {
	e.expect.returns = repositoryCreateUserReturn{first: first}
}

func (e *repositoryCreateUserExpecter) Match(matcher func(ctx context.Context, user User) bool) *repositoryCreateUserExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &repositoryCreateUserExpecterWithMatch{expect: e.expect}
}

func (e *repositoryCreateUserExpecter) MatchCtx(matcher func(ctx context.Context) bool) *repositoryCreateUserExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCtx"))
	}

	e.expect.matcher.ctx = matcher
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)
	e.expect.matcherHints["ctx"] = mockgenMessageMatchArgHint()
	return &repositoryCreateUserExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *repositoryCreateUserExpecter) MatchUser(matcher func(user User) bool) *repositoryCreateUserExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchUser"))
	}

	e.expect.matcher.user = matcher
	e.expect.matcherLocations["user"] = mockgenCallerLocation(2)
	e.expect.matcherHints["user"] = mockgenMessageMatchArgHint()
	return &repositoryCreateUserExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *repositoryCreateUserExpecter) With(ctx context.Context, user User) *repositoryCreateUserExpecterWithValue {
	e.WithCtx(ctx)
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)

	e.WithUser(user)
	e.expect.matcherLocations["user"] = mockgenCallerLocation(2)

	return &repositoryCreateUserExpecterWithValue{expect: e.expect}
}

func (e *repositoryCreateUserExpecter) WithCtx(ctx context.Context) *repositoryCreateUserExpecterWithValueArg {
	e.expect.matcher.ctx = mockgenBasicComparisonMatcher(ctx)
	e.expect.matcherWants["ctx"] = ctx
	e.expect.matcherMethods["ctx"] = "=="
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)

	return &repositoryCreateUserExpecterWithValueArg{expect: e.expect, target: e.target}
}

func (e *repositoryCreateUserExpecter) WithUser(user User) *repositoryCreateUserExpecterWithValueArg {
	e.expect.matcher.user = mockgenBasicComparisonMatcher(user)
	e.expect.matcherWants["user"] = user
	e.expect.matcherMethods["user"] = "=="
	e.expect.matcherLocations["user"] = mockgenCallerLocation(2)

	return &repositoryCreateUserExpecterWithValueArg{expect: e.expect, target: e.target}
}

type repositoryCreateUserExpecterWithMatch struct {
	expect *repositoryCreateUserExpect
}

func (e *repositoryCreateUserExpecterWithMatch) Return(first error) {
	e.expect.returns = repositoryCreateUserReturn{first: first}
}

type repositoryCreateUserExpecterWithMatchArg struct {
	expect *repositoryCreateUserExpect
	target *repositoryCreateUser
}

func (e *repositoryCreateUserExpecterWithMatchArg) Return(first error) {
	e.expect.returns = repositoryCreateUserReturn{first: first}
}

func (e *repositoryCreateUserExpecterWithMatchArg) MatchCtx(matcher func(ctx context.Context) bool) *repositoryCreateUserExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCtx"))
	}

	if e.expect.matcher.ctx != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCtx", e.expect.matcherLocations["ctx"]))
	}

	e.expect.matcher.ctx = matcher
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)
	e.expect.matcherHints["ctx"] = mockgenMessageMatchArgHint()
	return e
}

func (e *repositoryCreateUserExpecterWithMatchArg) MatchUser(matcher func(user User) bool) *repositoryCreateUserExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchUser"))
	}

	if e.expect.matcher.user != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchUser", e.expect.matcherLocations["user"]))
	}

	e.expect.matcher.user = matcher
	e.expect.matcherLocations["user"] = mockgenCallerLocation(2)
	e.expect.matcherHints["user"] = mockgenMessageMatchArgHint()
	return e
}

type repositoryCreateUserExpecterWithValue struct {
	expect *repositoryCreateUserExpect
}

func (e *repositoryCreateUserExpecterWithValue) Return(first error) {
	e.expect.returns = repositoryCreateUserReturn{first: first}
}

type repositoryCreateUserExpecterWithValueArg struct {
	expect *repositoryCreateUserExpect
	target *repositoryCreateUser
}

func (e *repositoryCreateUserExpecterWithValueArg) Return(first error) {
	e.expect.returns = repositoryCreateUserReturn{first: first}
}

func (e *repositoryCreateUserExpecterWithValueArg) WithCtx(ctx context.Context) *repositoryCreateUserExpecterWithValueArg {
	if e.expect.matcher.ctx != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCtx", e.expect.matcherLocations["ctx"]))
	}

	e.expect.matcher.ctx = mockgenBasicComparisonMatcher(ctx)
	e.expect.matcherWants["ctx"] = ctx
	e.expect.matcherMethods["ctx"] = "=="
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)

	return e
}

func (e *repositoryCreateUserExpecterWithValueArg) WithUser(user User) *repositoryCreateUserExpecterWithValueArg {
	if e.expect.matcher.user != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithUser", e.expect.matcherLocations["user"]))
	}

	e.expect.matcher.user = mockgenBasicComparisonMatcher(user)
	e.expect.matcherWants["user"] = user
	e.expect.matcherMethods["user"] = "=="
	e.expect.matcherLocations["user"] = mockgenCallerLocation(2)

	return e
}

type repositoryGetUsers struct {
	Calls        []repositoryGetUsersCall
	stub         func(ctx context.Context, tenantID string) ([]User, error)
	stubLocation string
	expects      []*repositoryGetUsersExpect
	verified     bool
}

func (m *repositoryGetUsers) methodName() string {
	return "GetUsers"
}

func (m *repositoryGetUsers) interfaceName() string {
	return "Repository"
}

func (m *repositoryGetUsers) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *repositoryGetUsers) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *repositoryGetUsers) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"ctx", v.Argument.ctx, "tenantID", v.Argument.tenantID}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *repositoryGetUsers) invokeStub(ctx context.Context, tenantID string) ([]User, error) {
	v0, v1 := m.stub(ctx, tenantID)
	return m.capture(repositoryGetUsersArgument{ctx: ctx, tenantID: tenantID}, repositoryGetUsersReturn{first: v0, second: v1})
}

func (m *repositoryGetUsers) invokeExpect(ctx context.Context, tenantID string) ([]User, error) {
	v0 := []any{"ctx", ctx, "tenantID", tenantID}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(ctx, tenantID) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "ctx", ctx, v2.matcher.ctx, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["ctx"])
	mockgenMatchArgument(m, v1, "tenantID", tenantID, v2.matcher.tenantID, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["tenantID"])

	return m.capture(repositoryGetUsersArgument{ctx: ctx, tenantID: tenantID}, v2.returns)
}

func (m *repositoryGetUsers) capture(args repositoryGetUsersArgument, returns repositoryGetUsersReturn) ([]User, error) {
	m.Calls = append(m.Calls, repositoryGetUsersCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *repositoryGetUsers) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type repositoryGetUsersCall struct {
	Location string
	Argument repositoryGetUsersArgument
	Return   repositoryGetUsersReturn
}

type repositoryGetUsersArgument struct {
	ctx      context.Context
	tenantID string
}

type repositoryGetUsersArgumentMatcher struct {
	ctx      func(ctx context.Context) bool
	tenantID func(tenantID string) bool
}

type repositoryGetUsersReturn struct {
	first  []User
	second error
}

type repositoryGetUsersExpect struct {
	match            func(ctx context.Context, tenantID string) bool
	matchLocation    string
	matcher          *repositoryGetUsersArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          repositoryGetUsersReturn
	location         string
	index            int
	tb               testing.TB
}

type repositoryGetUsersExpecter struct {
	expect *repositoryGetUsersExpect
	target *repositoryGetUsers
}

func (e *repositoryGetUsersExpecter) Return(first []User, second error) {
	e.expect.returns = repositoryGetUsersReturn{first: first, second: second}
}

func (e *repositoryGetUsersExpecter) Match(matcher func(ctx context.Context, tenantID string) bool) *repositoryGetUsersExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &repositoryGetUsersExpecterWithMatch{expect: e.expect}
}

func (e *repositoryGetUsersExpecter) MatchCtx(matcher func(ctx context.Context) bool) *repositoryGetUsersExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCtx"))
	}

	e.expect.matcher.ctx = matcher
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)
	e.expect.matcherHints["ctx"] = mockgenMessageMatchArgHint()
	return &repositoryGetUsersExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *repositoryGetUsersExpecter) MatchTenantID(matcher func(tenantID string) bool) *repositoryGetUsersExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchTenantID"))
	}

	e.expect.matcher.tenantID = matcher
	e.expect.matcherLocations["tenantID"] = mockgenCallerLocation(2)
	e.expect.matcherHints["tenantID"] = mockgenMessageMatchArgHint()
	return &repositoryGetUsersExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *repositoryGetUsersExpecter) With(ctx context.Context, tenantID string) *repositoryGetUsersExpecterWithValue {
	e.WithCtx(ctx)
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)

	e.WithTenantID(tenantID)
	e.expect.matcherLocations["tenantID"] = mockgenCallerLocation(2)

	return &repositoryGetUsersExpecterWithValue{expect: e.expect}
}

func (e *repositoryGetUsersExpecter) WithCtx(ctx context.Context) *repositoryGetUsersExpecterWithValueArg {
	e.expect.matcher.ctx = mockgenBasicComparisonMatcher(ctx)
	e.expect.matcherWants["ctx"] = ctx
	e.expect.matcherMethods["ctx"] = "=="
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)

	return &repositoryGetUsersExpecterWithValueArg{expect: e.expect, target: e.target}
}

func (e *repositoryGetUsersExpecter) WithTenantID(tenantID string) *repositoryGetUsersExpecterWithValueArg {
	e.expect.matcher.tenantID = mockgenBasicComparisonMatcher(tenantID)
	e.expect.matcherWants["tenantID"] = tenantID
	e.expect.matcherMethods["tenantID"] = "=="
	e.expect.matcherLocations["tenantID"] = mockgenCallerLocation(2)

	return &repositoryGetUsersExpecterWithValueArg{expect: e.expect, target: e.target}
}

type repositoryGetUsersExpecterWithMatch struct {
	expect *repositoryGetUsersExpect
}

func (e *repositoryGetUsersExpecterWithMatch) Return(first []User, second error) {
	e.expect.returns = repositoryGetUsersReturn{first: first, second: second}
}

type repositoryGetUsersExpecterWithMatchArg struct {
	expect *repositoryGetUsersExpect
	target *repositoryGetUsers
}

func (e *repositoryGetUsersExpecterWithMatchArg) Return(first []User, second error) {
	e.expect.returns = repositoryGetUsersReturn{first: first, second: second}
}

func (e *repositoryGetUsersExpecterWithMatchArg) MatchCtx(matcher func(ctx context.Context) bool) *repositoryGetUsersExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCtx"))
	}

	if e.expect.matcher.ctx != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCtx", e.expect.matcherLocations["ctx"]))
	}

	e.expect.matcher.ctx = matcher
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)
	e.expect.matcherHints["ctx"] = mockgenMessageMatchArgHint()
	return e
}

func (e *repositoryGetUsersExpecterWithMatchArg) MatchTenantID(matcher func(tenantID string) bool) *repositoryGetUsersExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchTenantID"))
	}

	if e.expect.matcher.tenantID != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchTenantID", e.expect.matcherLocations["tenantID"]))
	}

	e.expect.matcher.tenantID = matcher
	e.expect.matcherLocations["tenantID"] = mockgenCallerLocation(2)
	e.expect.matcherHints["tenantID"] = mockgenMessageMatchArgHint()
	return e
}

type repositoryGetUsersExpecterWithValue struct {
	expect *repositoryGetUsersExpect
}

func (e *repositoryGetUsersExpecterWithValue) Return(first []User, second error) {
	e.expect.returns = repositoryGetUsersReturn{first: first, second: second}
}

type repositoryGetUsersExpecterWithValueArg struct {
	expect *repositoryGetUsersExpect
	target *repositoryGetUsers
}

func (e *repositoryGetUsersExpecterWithValueArg) Return(first []User, second error) {
	e.expect.returns = repositoryGetUsersReturn{first: first, second: second}
}

func (e *repositoryGetUsersExpecterWithValueArg) WithCtx(ctx context.Context) *repositoryGetUsersExpecterWithValueArg {
	if e.expect.matcher.ctx != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCtx", e.expect.matcherLocations["ctx"]))
	}

	e.expect.matcher.ctx = mockgenBasicComparisonMatcher(ctx)
	e.expect.matcherWants["ctx"] = ctx
	e.expect.matcherMethods["ctx"] = "=="
	e.expect.matcherLocations["ctx"] = mockgenCallerLocation(2)

	return e
}

func (e *repositoryGetUsersExpecterWithValueArg) WithTenantID(tenantID string) *repositoryGetUsersExpecterWithValueArg {
	if e.expect.matcher.tenantID != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithTenantID", e.expect.matcherLocations["tenantID"]))
	}

	e.expect.matcher.tenantID = mockgenBasicComparisonMatcher(tenantID)
	e.expect.matcherWants["tenantID"] = tenantID
	e.expect.matcherMethods["tenantID"] = "=="
	e.expect.matcherLocations["tenantID"] = mockgenCallerLocation(2)

	return e
}

func testService() *service {
	return &service{td: &serviceTestDouble{location: mockgenCallerLocation(2)}}
}

type serviceTestDouble struct {
	location        string
	VeryComplicated *serviceVeryComplicated
}

type service struct {
	td *serviceTestDouble
}

func (m *service) STUB() *serviceStubber {
	return &serviceStubber{target: m}
}

func (m *service) VeryComplicated(id int) error {
	v0, v1, v2 := "Service", "VeryComplicated", "(id int) error"
	v3 := []any{"id", id}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.VeryComplicated; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(id)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

type serviceStubber struct {
	target *service
}

func (s *serviceStubber) VeryComplicated(stub func(id int) error) *serviceVeryComplicated {
	if s.target.td == nil {
		s.target.td = &serviceTestDouble{}
	}

	m := s.target.td.VeryComplicated
	if m == nil {
		m = &serviceVeryComplicated{stubLocation: mockgenCallerLocation(2)}
		s.target.td.VeryComplicated = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	m.stub = stub
	return m
}

type serviceVeryComplicated struct {
	Calls        []serviceVeryComplicatedCall
	stub         func(id int) error
	stubLocation string
}

func (m *serviceVeryComplicated) methodName() string {
	return "VeryComplicated"
}

func (m *serviceVeryComplicated) interfaceName() string {
	return "Service"
}

func (m *serviceVeryComplicated) fatal(index int, msg string) {}

func (m *serviceVeryComplicated) panic(msg string) {
	panic(msg)
}

func (m *serviceVeryComplicated) buildCallHistory(sb *strings.Builder, header string) {}

func (m *serviceVeryComplicated) invokeStub(id int) error {
	v0 := m.stub(id)
	return m.capture(serviceVeryComplicatedArgument{id: id}, serviceVeryComplicatedReturn{first: v0})
}

func (m *serviceVeryComplicated) capture(args serviceVeryComplicatedArgument, returns serviceVeryComplicatedReturn) error {
	m.Calls = append(m.Calls, serviceVeryComplicatedCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first
}

type serviceVeryComplicatedCall struct {
	Location string
	Argument serviceVeryComplicatedArgument
	Return   serviceVeryComplicatedReturn
}

type serviceVeryComplicatedArgument struct {
	id int
}

type serviceVeryComplicatedReturn struct {
	first error
}
